baseURL = "https://karthikeayan.github.io/"
languageCode = "en-us"
title = "Karthikeyan Sundararajan"
theme = "paper"

[params]
  # color style
  color = 'gray'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'karthikeayan'               # twitter.com/YOUR_TWITTER_ID
  github = 'karthikeayan'                 # github.com/YOUR_GITHUB_ID
  instagram = 'YOUR_INSTAGRAM_ID'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'karthikeyan-sundararajan/'             # linkedin.com/in/YOUR_LINKEDIN_ID
  mastodon = 'YOUR_MASTODON_LINK'           # e.g. 'https://mastodon.instance/@xxx'
  threads = '@YOUR_THREADS_ID'              # threads.net/@YOUR_THREADS_ID
  rss = false                                # show rss icon

  # home page profile
  avatar = 'https://avatars.githubusercontent.com/u/5030782?v=4&size=64'                 # gravatar email or image url
  name = 'Karthikeyan Sundararajan'
  bio = 'Truth triumphs, even without public support.'


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # RTL supprot
  # direction = "rtl"                         # RTL support for Right-to-left languages

